
FROM python:3.8-slim
WORKDIR /app
COPY . /app
#RUN pip install --trusted-host pypi.python.org Flask

#EXPOSE 5000

# Define environment variable
#ENV NAME World

# Run app.py when the container launches

CMD ["flask", "run"]
